version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
    - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12
    volumes:
      - stripe_postgres_data:/var/lib/postgresql/new_data/
    environment:
      - POSTGRES_USER=stripe_user
      - POSTGRES_PASSWORD=stripe_difficult_password
      - POSTGRES_DB=psql_db

volumes:
  stripe_postgres_data: