version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn Stripe.wsgi:application --bin 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - .:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - stripe_postgres_data:/var/lib/postgresql/new_data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
    - 80:80
    volumes:
    - static_volume:/home/app/web/static
    depends_on:
      - web
volumes:
  stripe_postgres_data:
  static_volume: