version: '3.7'

services:
  stripe_db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  stripe_web:
    build: .
    command: python /usr/src/stripe/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/stripe
    ports:
      - 8000:8000
    depends_on:
      - stripe_db
volumes:
  postgres_data: