# Generated by Django 3.1.2 on 2020-10-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StripeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
    ]
