# Generated by Django 3.1.2 on 2020-10-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StripeApp', '0003_auto_20201008_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='stripe_tax_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe ID'),
        ),
    ]
